#!/bin/bash
# : nb,v 1.12 2007/01/25 12:23:22 jettero Exp $
# vi:syntax=gentoo-init-d:

source /sbin/functions.sh
set -e; trap "eend 997" ERR

for i in *.diffs *.repo *.co; do
    if [ -d "$i" ]; then
        ebegin newking $i
        rm -rf $i
        eend $?
    fi
done

