#!/usr/bin/perl
# vi:tw=0:
# $Id: git_replay 39.1083.L58dgvaLEQ4iJZyUlpx7Xa+R2NI 2007-06-10 22:31:28 -0400 $

use strict;
use DBI;

die "$0 gitrepo svnco replaydb" unless @ARGV == 3;

my $gitrepo = shift @ARGV;
my $svnco   = shift @ARGV;
my $dbfile  = shift @ARGV; unless( -f $dbfile ) { open my $c, "|-", "sqlite3", $dbfile or die $!; local $/ = undef; print $c $_ while <DATA>; }

my $dbo = DBI->connect("dbi:SQLite:$dbfile", {RaiseError=>1});
my $ins = $dbo->prepare("insert into replay(commithash,parenthash) values(?,?)");
my $upd = $dbo->prepare("update replay set replayed=? where commithash=?");

if( not -d "$svnco/.git/" ) {
    system(qw(git clone --bare), $gitrepo, "$svnco/.git") == 0 or die;

    local $ENV{GIT_DIR} = "$svnco/.git";

    $dbo->begin_work;
    $dbo->do("delete from replay");
    open my $in, "-|", qw(git rev-list --all --parents) or die "error with revlist popen(): $!";
    while(<$in>) {
        my ($commit, $parent) = split /\s+/;

        $ins->execute( $commit, $parent );
    }
    close $in;
    $dbo->commit;
}

__DATA__
create table replay(
    commithash text, parenthash text, replayed int,
    unique(commithash)
);
