#!/bin/bash

source /sbin/functions.sh
set -e; trap "eend 997" ERR

ebegin "installing"
rm -f /home/svn/{git_replay,svn_builder}
einfon; install -v -m 0750 git_replay  /home/svn/
einfon; install -v -m 0750 svn_builder /home/svn/
eend $?

