#!/usr/bin/perl
# vi:tw=0:
# $Id: msgswp_test 21.337.d/NiMVnvhN4Osd9rUx4F0ghpzlE 2007-06-12 08:27:33 -0400 $

use strict;
use Tie::File;
use File::Copy qw(cp);

my $file = "s.co/sudoku/.msg";
my $elif = "./test.txt";

cp($file, $elif);

tie my @a, 'Tie::File', $elif or die $!;
push @a, "----- :: original git commit info :: -------------------";

while(1) {
    last if $a[0] =~ m/^\s*$/;

    push @a, shift @a;
}
