#!/usr/bin/perl
# vi:tw=0:
# $Id: msgswp_test 52.1072.4MHOOGMA9UCP/oyOVKyyTJyzjNw 2007-06-12 15:09:01 -0400 $

use strict;
use Tie::File;
use File::Copy qw(cp);

my $file = "/tmp/msg";

open my $out, ">$file" or die $!;
print $out q(commit ebe1b57263d5bc66c6e0097c73935dbb565253ad
Author: Paul Miller <jettero@voltar.org>
Date:   Wed Feb 28 07:32:59 2007 -0500

This commit is all about the newest rcskeywords version... It does dates
properly in the Id: and Date: fields.

);
close $out;

tie my @a, 'Tie::File', $file or die $!;
push @a, "----- :: original git commit info :: -------------------";

while(1) {
    last if $a[0] =~ m/^\s*$/;

    push @a, shift @a;
}
untie @a;


use Date::Parse;
use POSIX;

my ($date, $mdate);

open my $in, $file or die "error opening commit message: $!";
while(<$in>) {
    # Date:   Sat Mar 24 14:42:29 2007 -0400
    # 2007-06-11T23:38:06.463364Z
    if( m/^Date:\s+(\w{3}\s+\w{3}.+[+-]\d{4})\s*$/ ) {
        $mdate = $1;
        if( my $s = str2time($mdate) ) {
            $date = strftime('%Y-%m-%dT%H:%M:%S.000000Z', gmtime($s));
        }
        last;
    }
}
close $in;

warn "date=$date; mdate=$mdate";
