#!/bin/bash

source /sbin/functions.sh
set -e; trap "eend 997" ERR

ebegin "copying up"
scp -q git_replay index.xml svn_builder README /sbin/functions.sh voltar.org:voltar/git2svn
eend $?

ebegin "fixing perms"
ssh voltar.org '(cd voltar/git2svn; chmod 644 *)'
eend $?
