#!/bin/bash
# : nb,v 1.12 2007/01/25 12:23:22 jettero Exp $
# vi:syntax=gentoo-init-d:

source /sbin/functions.sh
set -e; trap "eend 997" ERR

rdir="$1"; shift; if [ -z "$rdir" ]; then eerror "rdir not set"; exit 1; fi
cdir="$1"; shift; if [ -z "$cdir" ]; then eerror "cdir not set"; exit 1; fi

if [ ! -d $rdir ]; then
    ebegin "creating svn repo"
    svnadmin create $rdir
    eend $?
fi

if [ ! -d $cdir ]; then
    if [[ ! $rdir =~ "^/" ]]; then
        einfo "converting rdir $rdir => \`pwd\`/$rdir"
        rdir=`pwd`/$rdir
    fi

    ebegin "checking out the new svn"
    einfon "svn msg: ";
    svn co file://$rdir $cdir
    eend $?
fi

while [ -n "$1" ]; do
    subdir=$1; shift;

    if [ ! -d $cdir/$subdir ]; then
        ebegin "building subdir=$subdir";
        (cd $cdir && mkdir $subdir && svn add $subdir)
        eend $?
    fi
done

