#!/bin/bash

source /sbin/functions.sh
set -e; trap "eend 997" ERR

# svn_builder repo_dir checked_out_dir project1 project2 project3 project4 project5

rdir="$1"; shift; if [ -z "$rdir" ]; then eerror "rdir not set"; exit 1; fi
cdir="$1"; shift; if [ -z "$cdir" ]; then eerror "cdir not set"; exit 1; fi

if [ ! -d $rdir ]; then
    ebegin "creating svn repo"
    svnadmin create $rdir
    eend $?

    prpc=$rdir/hooks/pre-revprop-change
    ebegin "installing pre-revprop-hook";
    cp $prpc.tmpl $prpc
    perl -i -pe 's/svn:log/svn:date/g' $prpc
    chmod 755 $prpc
    eend $?
fi

if [ ! -d $cdir ]; then
    if [[ ! $rdir =~ "^/" ]]; then
        einfo "converting rdir $rdir => \`pwd\`/$rdir"
        rdir=`pwd`/$rdir
    fi

    ebegin "checking out the new svn"
    einfon "svn msg: ";
    svn co file://$rdir $cdir
    eend $?
fi

while [ -n "$1" ]; do
    subdir=$1; shift;

    if [ ! -d $cdir/$subdir ]; then
        ebegin "building subdir=$subdir";
        einfon "svn msg: "
        (cd $cdir && mkdir $subdir && svn add $subdir)
        eend $?
    fi
done

(cd $cdir && svn commit -m "initial build by svn_builder")
