#!/bin/bash
# : nb,v 1.12 2007/01/25 12:23:22 jettero Exp $
# vi:syntax=gentoo-init-d:

source /sbin/functions.sh
set -e; trap "eend 997" ERR

ddir="$1"; shift; if [ -z "$ddir" ]; then eerror "ddir not set"; exit 1; fi
rdir="$1"; shift; if [ -z "$rdir" ]; then eerror "rdir not set"; exit 1; fi
cdir="$1"; shift; if [ -z "$cdir" ]; then eerror "cdir not set"; exit 1; fi

ebegin "creating svn repo"
svnadmin create $rdir
eend $?

if [[ ! $rdir =~ "^/" ]]; then
    einfo "converting rdir $rdir => \`pwd\`/$rdir"
    rdir=`pwd`/$rdir
fi

ebegin "checking out the new svn"
einfon "svn msg: ";
svn co file://$rdir $cdir
eend $?

